### ISSUE TITLE
Intro to Colab Demo - What Should Be Included?

### ISSUE THREAD

**Issue by pbeens** [pbeens/OTF-Data-Analysis-2021-05#1]
What should be included in a first demo of Colab?

Page: https://github.com/pbeens/OTF-Data-Analysis-2021-05/tree/main/demos/1-colab-demo

**Comment by mrghutchison** [comment]
First demo should include how to bring existing open data into colab for analysis. A very clean and simple dataset would be great.

**Comment by pbeens** [comment]
> First demo should include how to bring existing open data into colab for analysis. A very clean and simple dataset would be great.

That will be in demo #2:
https://github.com/pbeens/OTF-Data-Analysis-2021-05/tree/main/demos/2-wiki-line-chart

I recreate the line chart on this page, importing the table that's on the page:
https://en.wikipedia.org/wiki/Line_chart

Q. Do you receive a notification that this was posted?

**Comment by pbeens** [comment]
A great resource to refer to:
https://colab.research.google.com/notebooks/welcome.ipynb

**Comment by mrghutchison** [comment]
Lots of good ideas in that resource.

**Comment by mrghutchison** [comment]
I was thinking about collecting some acceleration data from a free falling microbit and we could then use the data in a notebook for analysis of the acceleration behaviour. What do you think? @pbeens

**Comment by mrghutchison** [comment]
I have not used issues before. Is there a close option on your side? I don't see anything here.

**Comment by pbeens** [comment]
> I was thinking about collecting some acceleration data from a free falling microbit and we could then use the data in a notebook for analysis of the acceleration behaviour. What do you think? @pbeens

@mrghutchison That's a great idea! Take some pictures that we can include in the slideshow, give me the CSV data to put in the repository, and we'll include it. That's a perfect application for it! 

Bonus: include relevant expectations that this would apply to.
